# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_gen/control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto_gen/control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto_gen/control.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\x08KeyInput\x12\x11\n\tkey_value\x18\x01 \x01(\t2L\n\x0fKeyboardService\x12\x39\n\x12SendKeyboardStream\x12\t.KeyInput\x1a\x16.google.protobuf.Empty(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_gen.control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYINPUT']._serialized_start=56
  _globals['_KEYINPUT']._serialized_end=85
  _globals['_KEYBOARDSERVICE']._serialized_start=87
  _globals['_KEYBOARDSERVICE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
